apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kind-storage1/jenkins1
  storageClassName: jenkins-storage1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: jenkins-storage1
